### ISSUE TITLE
Pros. and Cons.

### ISSUE THREAD

**Issue by a-a-k** [keeper013/Oasis#1]
Could you please compare your mapper with others in user-friendly format?

**Comment by keeper013** [comment]
So far I haven't had the time to investigate what kind of features other mappers provide or how they perform, as I'm the sole contributor to this project, and I'm in the mean time tied up with other projects.

Regarding this mapper, it's designed to provide more convenience to the special use case when we map DTOs to entity framework entities, the normal use case for mapping one instance to another is like a must-have feature for common mapper. I'm only guessing that for general cases it's way less powerful than AutoMapper.
